version: '3.8'

services:
  epc-resto:
    build: .                # build from Dockerfile in current directory
    container_name: epc-resto
    working_dir: /service/app
    command: npm run start:dev
    ports:
      - "3000:3000"         # map container port 3000 to host
    env_file:
      - ./.env              # optional, include your env variables
    volumes:
      - ./:/service/app     # mount current directory for live code changes

  mongo:
    image: mongo:6
    container_name: epc-mongo
    volumes:
      - ./mongo-data/:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 2G

  redis:
    image: redis:6.2
    container_name: epc-redis
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --include /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      # Redis ACL username/password
      - REDIS_USER=epcuser
      - REDIS_PASSWORD=epcpassword
    deploy:
      resources:
        limits:
          memory: 2G